language: csharp
dist: trusty
mono: none
dotnet: 1.0.1
script:
  - cd src
  - dotnet restore
  - dotnet build
  - cd ..
  - cd tests
  - dotnet restore
  - dotnet build
  - dotnet test

notifications:
  email: false